GET http://localhost:3003/getAll
Content-Type: application/json


###

POST http://localhost:3003/createUser
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria.co@hotweels.com",
    "password": "cafeteira"
}