GET http://localhost:3003/all
Content-Type: application/json

###

POST http://localhost:3003/createUser
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria.co@hotweels.com",
    "password": "cafeteira"
}


###
DELETE http://localhost:3003/id
Content-Type: application/json

{
    "id": "1674004801752"
}